<?php echo $this->doctype(); ?>

<html lang="<?php Locale::getDisplayVariant(Locale::getDefault());?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/app.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/modernizr.js'))
        ; ?>

    </head>
    <body>
    <div class="background-media">
        <div class="background">
            <div class="media">
                <div id="header-slider">
                    <div><img src="https://erstellbar.de/images/top.jpg" alt=""/></div>
                    <div><img src="https://erstellbar.de/images/reference.jpg" alt=""/></div>
                    <div><img src="https://erstellbar.de/images/connect.jpg" alt=""/></div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="row">
                <div class="small-12 columns">
                    <div class="">
                        <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
                        <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
                        <p><a class="button success large radius" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
            <div class="row">
                <div class="small-12 columns">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <div class="row">
                    <div class="small-12 columns">
                        <p>&copy; 2013 - <?php echo date('Y') ?> by Erstellbar. <?php echo $this->translate('All rights reserved.') ?></p>
                        <?php echo $this->localeMenu()->setUlClass('square'); ?>
                    </div>
                </div>
            </footer>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/lib/slick.min.js'))
            ->prependFile($this->basePath('js/lib/foundation.js'))
            ->prependFile($this->basePath('js/lib/jquery.js'))
            ; ?>
    <script>
        $(document).foundation();
    </script>
    </body>
</html>
